import type { Metadata } from "next";
import "./globals.css";
import CustomProviders from "@/components/CustomProviders";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Hiperhire",
  description: "Generated by Hiperhire",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <CustomProviders>{children}</CustomProviders>
      </body>
    </html>
  );
}
